/**
 * @file audio_stats.h
 * @brief Audio performance statistics tracking
 */

#ifndef AUDIO_STATS_H
#define AUDIO_STATS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Audio performance statistics structure
 */
typedef struct {
    /* Counters (reset each second) */
    uint32_t samples_generated;      /* Samples generated by APU */
    uint32_t samples_queued;         /* Samples actually queued to SDL */
    uint32_t samples_dropped;        /* Samples dropped due to full queue */
    uint32_t batches_queued;         /* Number of batches queued */
    uint32_t batches_dropped;        /* Number of batches dropped */
    
    /* Current state */
    uint32_t queue_size_bytes;       /* Current SDL audio queue size */
    uint32_t queue_size_samples;     /* Queue size in stereo samples */
    float queue_latency_ms;          /* Estimated latency from queue */
    
    /* Timing */
    uint64_t last_reset_time_ms;     /* When counters were last reset */
    float sample_rate_actual;        /* Measured sample rate */
    
    /* Per-second snapshots (for display) */
    uint32_t last_samples_generated;
    uint32_t last_samples_dropped;
    uint32_t last_queue_underruns;
    
    /* Running totals */
    uint64_t total_samples_generated;
    uint64_t total_samples_dropped;
    uint64_t total_queue_underruns;
    
    /* Flags */
    bool enabled;
    bool log_to_console;
} AudioStats;

/* Global stats instance */
extern AudioStats g_audio_stats;

/**
 * Initialize audio statistics tracking
 */
void audio_stats_init(void);

/**
 * Reset per-second counters (call this once per second)
 */
void audio_stats_tick(uint64_t current_time_ms);

/**
 * Record a sample generation event
 */
static inline void audio_stats_sample_generated(void) {
    if (g_audio_stats.enabled) {
        g_audio_stats.samples_generated++;
        g_audio_stats.total_samples_generated++;
    }
}

/**
 * Record samples being queued to SDL
 */
static inline void audio_stats_samples_queued(uint32_t count) {
    if (g_audio_stats.enabled) {
        g_audio_stats.samples_queued += count;
        g_audio_stats.batches_queued++;
    }
}

/**
 * Record samples being dropped
 */
static inline void audio_stats_samples_dropped(uint32_t count) {
    if (g_audio_stats.enabled) {
        g_audio_stats.samples_dropped += count;
        g_audio_stats.total_samples_dropped += count;
        g_audio_stats.batches_dropped++;
    }
}

/**
 * Update queue state from SDL
 */
void audio_stats_update_queue(uint32_t queue_size_bytes, int sample_rate);

/**
 * Record a queue underrun (SDL ran out of data)
 */
static inline void audio_stats_underrun(void) {
    if (g_audio_stats.enabled) {
        g_audio_stats.last_queue_underruns++;
        g_audio_stats.total_queue_underruns++;
    }
}

/**
 * Print current statistics to console
 */
void audio_stats_print(void);

/**
 * Get formatted statistics string for ImGui
 */
const char* audio_stats_get_summary(void);

#ifdef __cplusplus
}
#endif

#endif /* AUDIO_STATS_H */
