/**
 * @file c_emitter.cpp
 * @brief C code emitter implementation (MVP)
 */

#include "recompiler/codegen/c_emitter.h"
#include <iomanip>
#include <iostream>
#include <fstream>
#include <filesystem>
#include <algorithm>
#include <set>

namespace nesrecomp {
namespace codegen {

/* ============================================================================
 * CEmitter Constructor
 * ========================================================================== */

CEmitter::CEmitter(std::ostream& output, const GeneratorOptions& options)
    : out_(output), options_(options), indent_level_(0) {}

/* ============================================================================
 * Helper Methods
 * ========================================================================== */

void CEmitter::emit_indent() {
    for (int i = 0; i < indent_level_; i++) {
        out_ << "    ";
    }
}

void CEmitter::emit_line(const std::string& line) {
    emit_indent();
    out_ << line << "\n";
}

// 6502 register names
const char* CEmitter::reg8_name(uint8_t reg) {
    static const char* names[] = {"A", "X", "Y", "SP"};
    return reg < 4 ? names[reg] : "?";
}

const char* CEmitter::reg16_name(uint8_t reg) {
    (void)reg;  // 6502 doesn't use 16-bit register pairs like GB
    return "?";
}

const char* CEmitter::condition_code(uint8_t cc) {
    static const char* names[] = {"N", "P", "Z", "NZ", "C", "NC", "V", "NV"};
    return cc < 8 ? names[cc] : "?";
}

const char* CEmitter::condition_expr(uint8_t cc) {
    switch (cc) {
        case 0: return "ctx->f_n";       // N (Negative)
        case 1: return "!ctx->f_n";      // P (Positive)
        case 2: return "ctx->f_z";       // Z (Zero)
        case 3: return "!ctx->f_z";      // NZ (Not Zero)
        case 4: return "ctx->f_c";       // C (Carry)
        case 5: return "!ctx->f_c";      // NC (Not Carry)
        case 6: return "ctx->f_v";       // V (Overflow)
        case 7: return "!ctx->f_v";      // NV (Not Overflow)
        default: return "true";
    }
}

/* ============================================================================
 * Program Structure
 * ========================================================================== */

void CEmitter::begin_program(const std::string& name) {
    out_ << "/* Generated by nesrecomp from " << name << " */\n";
    out_ << "#include \"nesrt.h\"\n\n";
    current_function_ = "";
}

void CEmitter::end_program() {
    out_ << "\n/* End of generated code */\n";
}

void CEmitter::begin_function(const std::string& name, uint8_t bank, uint16_t addr) {
    out_ << "\n/* Function at ";
    if (bank > 0) {
        out_ << std::hex << std::setfill('0') << std::setw(2) << (int)bank << ":";
    }
    out_ << std::hex << std::setfill('0') << std::setw(4) << addr << std::dec << " */\n";
    out_ << "void " << name << "(NESContext* ctx) {\n";
    current_function_ = name;
    indent_level_ = 1;
}

void CEmitter::end_function() {
    indent_level_ = 0;
    out_ << "}\n";
    current_function_ = "";
}

void CEmitter::emit_label(const std::string& label) {
    // Labels are at indent 0, code at indent 1
    out_ << label << ":\n";
}

/* ============================================================================
 * Data Movement (6502-specific)
 * ========================================================================== */

void CEmitter::emit_mov_reg_reg(uint8_t dst, uint8_t src) {
    emit_indent();
    out_ << "ctx->" << reg8_name(dst) << " = ctx->" << reg8_name(src) << ";\n";
}

void CEmitter::emit_mov_reg_imm8(uint8_t dst, uint8_t imm) {
    emit_indent();
    out_ << "ctx->" << reg8_name(dst) << " = 0x" << std::hex << std::setfill('0')
         << std::setw(2) << (int)imm << std::dec << ";\n";
}

void CEmitter::emit_mov_reg16_imm16(uint8_t dst, uint16_t imm) {
    (void)dst; (void)imm;  // 6502 doesn't have 16-bit register moves
}

void CEmitter::emit_load8_addr(uint8_t dst, uint16_t addr) {
    emit_indent();
    out_ << "ctx->" << reg8_name(dst) << " = nes_read8(ctx, 0x" << std::hex
         << std::setfill('0') << std::setw(4) << addr << std::dec << ");\n";
}

void CEmitter::emit_load8_reg(uint8_t dst, uint8_t addr_reg) {
    (void)dst; (void)addr_reg;  // 6502 uses different addressing modes
}

void CEmitter::emit_load16_addr(uint8_t dst, uint16_t addr) {
    (void)dst; (void)addr;  // 6502 doesn't have 16-bit loads
}

void CEmitter::emit_store8_addr(uint16_t addr, uint8_t src) {
    emit_indent();
    out_ << "nes_write8(ctx, 0x" << std::hex << std::setfill('0') << std::setw(4)
         << addr << std::dec << ", ctx->" << reg8_name(src) << ");\n";
}

void CEmitter::emit_store8_reg(uint8_t addr_reg, uint8_t src) {
    (void)addr_reg; (void)src;  // 6502 uses different addressing modes
}

void CEmitter::emit_store16_addr(uint16_t addr, uint8_t src) {
    (void)addr; (void)src;  // 6502 doesn't have 16-bit stores
}

void CEmitter::emit_push(uint8_t reg16) {
    (void)reg16;  // 6502 only pushes A and SR
}

void CEmitter::emit_pop(uint8_t reg16) {
    (void)reg16;  // 6502 only pops A and SR
}

/* ============================================================================
 * ALU Operations (6502-specific)
 * ========================================================================== */

void CEmitter::emit_add_a_reg(uint8_t src) {
    emit_indent();
    out_ << "nes_add8(ctx, ctx->" << reg8_name(src) << ");\n";
}

void CEmitter::emit_add_a_imm(uint8_t imm) {
    emit_indent();
    out_ << "nes_add8(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
         << (int)imm << std::dec << ");\n";
}

void CEmitter::emit_adc_a_reg(uint8_t src) {
    emit_indent();
    out_ << "nes6502_adc(ctx, ctx->" << reg8_name(src) << ");\n";
}

void CEmitter::emit_adc_a_imm(uint8_t imm) {
    emit_indent();
    out_ << "nes6502_adc(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
         << (int)imm << std::dec << ");\n";
}

void CEmitter::emit_sub_a_reg(uint8_t src) {
    emit_indent();
    out_ << "nes_sub8(ctx, ctx->" << reg8_name(src) << ");\n";
}

void CEmitter::emit_sub_a_imm(uint8_t imm) {
    emit_indent();
    out_ << "nes_sub8(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
         << (int)imm << std::dec << ");\n";
}

void CEmitter::emit_sbc_a_reg(uint8_t src) {
    emit_indent();
    out_ << "nes6502_sbc(ctx, ctx->" << reg8_name(src) << ");\n";
}

void CEmitter::emit_sbc_a_imm(uint8_t imm) {
    emit_indent();
    out_ << "nes6502_sbc(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
         << (int)imm << std::dec << ");\n";
}

void CEmitter::emit_and_a_reg(uint8_t src) {
    emit_indent();
    out_ << "nes6502_and(ctx, ctx->" << reg8_name(src) << ");\n";
}

void CEmitter::emit_and_a_imm(uint8_t imm) {
    emit_indent();
    out_ << "nes6502_and(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
         << (int)imm << std::dec << ");\n";
}

void CEmitter::emit_or_a_reg(uint8_t src) {
    emit_indent();
    out_ << "nes6502_ora(ctx, ctx->" << reg8_name(src) << ");\n";
}

void CEmitter::emit_or_a_imm(uint8_t imm) {
    emit_indent();
    out_ << "nes6502_ora(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
         << (int)imm << std::dec << ");\n";
}

void CEmitter::emit_xor_a_reg(uint8_t src) {
    emit_indent();
    out_ << "nes6502_eor(ctx, ctx->" << reg8_name(src) << ");\n";
}

void CEmitter::emit_xor_a_imm(uint8_t imm) {
    emit_indent();
    out_ << "nes6502_eor(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
         << (int)imm << std::dec << ");\n";
}

void CEmitter::emit_cp_a_reg(uint8_t src) {
    emit_indent();
    out_ << "nes6502_cmp(ctx, ctx->" << reg8_name(src) << ");\n";
}

void CEmitter::emit_cp_a_imm(uint8_t imm) {
    emit_indent();
    out_ << "nes6502_cmp(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
         << (int)imm << std::dec << ");\n";
}

void CEmitter::emit_inc_reg8(uint8_t reg) {
    emit_indent();
    out_ << "ctx->" << reg8_name(reg) << " = nes_inc8(ctx, ctx->" << reg8_name(reg) << ");\n";
}

void CEmitter::emit_dec_reg8(uint8_t reg) {
    emit_indent();
    out_ << "ctx->" << reg8_name(reg) << " = nes_dec8(ctx, ctx->" << reg8_name(reg) << ");\n";
}

void CEmitter::emit_inc_reg16(uint8_t reg) {
    (void)reg;  // 6502 uses INC/DEC on memory or specific registers
}

void CEmitter::emit_dec_reg16(uint8_t reg) {
    (void)reg;  // 6502 uses INC/DEC on memory or specific registers
}

void CEmitter::emit_inc_mem_hl() {
    emit_line("/* INC memory - use INC opcode */");
}

void CEmitter::emit_dec_mem_hl() {
    emit_line("/* DEC memory - use DEC opcode */");
}

void CEmitter::emit_add_hl_reg16(uint8_t src) {
    (void)src;  // 6502 doesn't have HL register pair
}

void CEmitter::emit_add_sp_imm8(int8_t offset) {
    emit_indent();
    out_ << "nes_add_sp(ctx, " << (int)offset << ");\n";
}

/* ============================================================================
 * Bit Operations (6502-specific)
 * ========================================================================== */

// 6502 uses ASL, LSR, ROL, ROR for shifts/rotates
// BIT instruction tests bits but doesn't modify memory

void CEmitter::emit_rlc_reg(uint8_t reg) {
    (void)reg;  // 6502 uses ROL instead of RLC
}

void CEmitter::emit_rrc_reg(uint8_t reg) {
    (void)reg;  // 6502 uses ROR instead of RRC
}

void CEmitter::emit_rl_reg(uint8_t reg) {
    (void)reg;  // 6502 uses ROL
}

void CEmitter::emit_rr_reg(uint8_t reg) {
    (void)reg;  // 6502 uses ROR
}

void CEmitter::emit_sla_reg(uint8_t reg) {
    (void)reg;  // 6502 uses ASL
}

void CEmitter::emit_sra_reg(uint8_t reg) {
    (void)reg;  // 6502 doesn't have arithmetic shift right
}

void CEmitter::emit_srl_reg(uint8_t reg) {
    (void)reg;  // 6502 uses LSR
}

void CEmitter::emit_swap_reg(uint8_t reg) {
    (void)reg;  // 6502 doesn't have SWAP
}

void CEmitter::emit_bit_n_reg(uint8_t bit, uint8_t reg) {
    (void)bit; (void)reg;  // 6502 BIT works differently (tests memory against A)
}

void CEmitter::emit_set_n_reg(uint8_t bit, uint8_t reg) {
    (void)bit; (void)reg;  // 6502 doesn't have SET instruction
}

void CEmitter::emit_res_n_reg(uint8_t bit, uint8_t reg) {
    (void)bit; (void)reg;  // 6502 doesn't have RES instruction
}

void CEmitter::emit_rlc_hl() { emit_line("/* RLC - use ROL for 6502 */"); }
void CEmitter::emit_rrc_hl() { emit_line("/* RRC - use ROR for 6502 */"); }
void CEmitter::emit_rl_hl() { emit_line("/* RL - use ROL for 6502 */"); }
void CEmitter::emit_rr_hl() { emit_line("/* RR - use ROR for 6502 */"); }
void CEmitter::emit_sla_hl() { emit_line("/* SLA - use ASL for 6502 */"); }
void CEmitter::emit_sra_hl() { emit_line("/* SRA - not available on 6502 */"); }
void CEmitter::emit_srl_hl() { emit_line("/* SRL - use LSR for 6502 */"); }
void CEmitter::emit_swap_hl() { emit_line("/* SWAP - not available on 6502 */"); }

void CEmitter::emit_bit_n_hl(uint8_t bit) {
    (void)bit;  // 6502 BIT works differently
}

void CEmitter::emit_set_n_hl(uint8_t bit) {
    (void)bit;  // 6502 doesn't have SET
}

void CEmitter::emit_res_n_hl(uint8_t bit) {
    (void)bit;  // 6502 doesn't have RES
}

void CEmitter::emit_rlca() { emit_line("/* RLCA - use ASL A for 6502 */"); }
void CEmitter::emit_rrca() { emit_line("/* RRCA - use LSR A for 6502 */"); }
void CEmitter::emit_rla() { emit_line("/* RLA - use ROL A for 6502 */"); }
void CEmitter::emit_rra() { emit_line("/* RRA - use ROR A for 6502 */"); }

/* ============================================================================
 * Control Flow (6502-specific)
 * ========================================================================== */

void CEmitter::emit_jump(const std::string& label) {
    emit_indent();
    out_ << "goto " << label << ";\n";
}

void CEmitter::emit_jump_cc(uint8_t cc, const std::string& label,
                            const std::string& fallthrough_label) {
    emit_indent();
    out_ << "if (" << condition_expr(cc) << ") goto " << label << ";\n";
    (void)fallthrough_label;  // Not needed with goto
}

void CEmitter::emit_jump_hl() {
    emit_line("nesrt_jump_hl(ctx); return;");
}

void CEmitter::emit_jr(int8_t offset, const std::string& label) {
    (void)offset;  // Using label instead
    emit_indent();
    out_ << "goto " << label << ";\n";
}

void CEmitter::emit_jr_cc(uint8_t cc, int8_t offset, const std::string& label,
                          const std::string& fallthrough_label) {
    (void)offset;
    emit_jump_cc(cc, label, fallthrough_label);
}

void CEmitter::emit_call(const std::string& func_name) {
    emit_indent();
    out_ << func_name << "(ctx);\n";
}

void CEmitter::emit_call_cc(uint8_t cc, const std::string& func_name,
                            const std::string& fallthrough_label) {
    emit_indent();
    out_ << "if (" << condition_expr(cc) << ") " << func_name << "(ctx);\n";
    (void)fallthrough_label;
}

void CEmitter::emit_rst(uint8_t vector) {
    emit_indent();
    out_ << "nes_rst(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
         << (int)vector << std::dec << ");\n";
}

void CEmitter::emit_ret() {
    emit_line("return;");
}

void CEmitter::emit_ret_cc(uint8_t cc, const std::string& fallthrough_label) {
    emit_indent();
    out_ << "if (" << condition_expr(cc) << ") return;\n";
    (void)fallthrough_label;
}

void CEmitter::emit_reti() {
    emit_line("ctx->ime = 1;");
    emit_line("return;");
}

void CEmitter::emit_bank_call(uint8_t target_bank, const std::string& func_name) {
    (void)target_bank; (void)func_name;  // 6502 doesn't have bank switching like GB
}

void CEmitter::emit_bank_dispatch(uint16_t addr) {
    emit_indent();
    out_ << "nes_dispatch(ctx, 0x" << std::hex << std::setfill('0')
         << std::setw(4) << addr << std::dec << ");\n";
}

/* ============================================================================
 * Special Instructions (6502-specific)
 * ========================================================================== */

void CEmitter::emit_nop() {
    // No-op - can emit nothing or a comment
    if (options_.emit_comments) {
        emit_line("/* NOP */");
    }
}

void CEmitter::emit_halt(uint16_t next_pc) {
    (void)next_pc;  // 6502 doesn't have HALT
}

void CEmitter::emit_stop() { 
    emit_line("/* STOP - not available on 6502 */"); 
}

void CEmitter::emit_di() { 
    emit_line("ctx->f_i = 1;");  // SEI - Set Interrupt Disable
}

void CEmitter::emit_ei() { 
    emit_line("ctx->f_i = 0;");  // CLI - Clear Interrupt Disable
}

void CEmitter::emit_daa() { 
    emit_line("/* DAA - not available on 6502 (use SED/CLD for decimal mode) */"); 
}

void CEmitter::emit_cpl() { 
    emit_line("ctx->a = ~ctx->a;");  // Equivalent to EOR #$FF
}

void CEmitter::emit_ccf() { 
    emit_line("ctx->f_c = !ctx->f_c;");  // No direct 6502 equivalent
}

void CEmitter::emit_scf() { 
    emit_line("ctx->f_c = 1;");  // SEC - Set Carry Flag
}

/* ============================================================================
 * I/O (6502-specific)
 * ========================================================================== */

void CEmitter::emit_ldh_a_n(uint8_t offset) {
    emit_indent();
    out_ << "ctx->a = nes_read8(ctx, 0x" << std::hex << std::setfill('0')
         << std::setw(4) << (0x2000 + offset) << std::dec << ");\n";  // NES PPU registers start at 0x2000
}

void CEmitter::emit_ldh_n_a(uint8_t offset) {
    emit_indent();
    out_ << "nes_write8(ctx, 0x" << std::hex << std::setfill('0')
         << std::setw(4) << (0x2000 + offset) << std::dec << ", ctx->a);\n";
}

void CEmitter::emit_ldh_a_c() {
    emit_line("ctx->a = nes_read8(ctx, 0x2000 + ctx->c);");
}

void CEmitter::emit_ldh_c_a() {
    emit_line("nes_write8(ctx, 0x2000 + ctx->c, ctx->a);");
}

/* ============================================================================
 * Memory with increment/decrement (6502-specific)
 * ========================================================================== */

void CEmitter::emit_ldi_a_hl() { emit_line("/* LDI - use indexed addressing for 6502 */"); }
void CEmitter::emit_ldd_a_hl() { emit_line("/* LDD - use indexed addressing for 6502 */"); }
void CEmitter::emit_ldi_hl_a() { emit_line("/* LDI - use indexed addressing for 6502 */"); }
void CEmitter::emit_ldd_hl_a() { emit_line("/* LDD - use indexed addressing for 6502 */"); }

/* ============================================================================
 * Debug/Comments
 * ========================================================================== */

void CEmitter::emit_comment(const std::string& comment) {
    if (options_.emit_comments) {
        emit_indent();
        out_ << "/* " << comment << " */\n";
    }
}

void CEmitter::emit_source_location(uint8_t bank, uint16_t addr) {
    if (options_.emit_address_comments) {
        emit_indent();
        out_ << "/* ";
        if (bank > 0) {
            out_ << std::hex << std::setfill('0') << std::setw(2) << (int)bank << ":";
        }
        out_ << std::hex << std::setfill('0') << std::setw(4) << addr << std::dec << " */\n";
    }
}

/* ============================================================================
 * Cycle Counting
 * ========================================================================== */

void CEmitter::emit_add_cycles(uint8_t cycles) {
    if (options_.emit_cycle_counting) {
        emit_indent();
        out_ << "nes_tick(ctx, " << (int)cycles << ");\n";
        emit_indent();
        out_ << "if (ctx->stopped) return;\n";
    }
}

void CEmitter::emit_yield_check() {
    emit_line("if (ctx->cycles >= ctx->cycle_limit) return;");
}

/* ============================================================================
 * Output Generation Functions
 * ========================================================================== */

// 6502 register names (0=A, 1=X, 2=Y, 3=SP)
static const char* reg8_6502_names[] = {"a", "x", "y", "sp"};
static const char* cond_6502_names[] = {"N", "P", "Z", "NZ", "C", "NC", "V", "NV"};

static const char* get_reg8_6502_name(int idx) {
    if (idx < 0 || idx > 3) return nullptr;
    return reg8_6502_names[idx];
}

static const char* get_cond_expr_6502(uint8_t cc) {
    switch (cc) {
        case 0: return "ctx->f_n";       // N (Negative)
        case 1: return "!ctx->f_n";      // P (Positive)
        case 2: return "ctx->f_z";       // Z (Zero)
        case 3: return "!ctx->f_z";      // NZ (Not Zero)
        case 4: return "ctx->f_c";       // C (Carry)
        case 5: return "!ctx->f_c";      // NC (Not Carry)
        case 6: return "ctx->f_v";       // V (Overflow)
        case 7: return "!ctx->f_v";      // NV (Not Overflow)
        default: return "true";
    }
}

static void emit_ir_instruction(std::ostream& out, const ir::IRInstruction& instr,
                                const ir::Program& program, int indent,
                                const GeneratorOptions& options,
                                uint16_t next_pc_val,
                                uint32_t group_cycles,
                                bool is_last_in_group,
                                const std::string& current_func_name,
                                const std::set<std::string>& inlineable_functions);

static void emit_ir_instruction(std::ostream& out, const ir::IRInstruction& instr,
                                const ir::Program& program, int indent,
                                const GeneratorOptions& options,
                                uint16_t next_pc_val,
                                uint32_t group_cycles,
                                bool is_last_in_group,
                                const std::string& current_func_name,
                                const std::set<std::string>& inlineable_functions) {
    auto emit_indent = [&out, indent]() {
        for (int i = 0; i < indent; i++) out << "    ";
    };

    // Emit source location comment if enabled
    if (options.emit_address_comments && instr.has_source_location) {
        emit_indent();
        out << "/* " << std::hex << std::setfill('0');
        if (instr.source_bank > 0) {
            out << std::setw(2) << (int)instr.source_bank << ":";
        }
        out << std::setw(4) << instr.source_address << std::dec << " */ ";
    }

    // Comment (usually disassembly)
    if (!instr.comment.empty() && options.emit_comments) {
        emit_indent();
        out << "/* " << instr.comment << " */\n";
        return;  // Comment-only instruction
    }

    emit_indent();

    switch (instr.opcode) {
        // === No-op ===
        case ir::Opcode::NOP:
            out << "/* NOP */\n";
            break;

        // === Data Movement - Load Immediate ===
        case ir::Opcode::LOAD_A_IMM:
            out << "ctx->a = 0x" << std::hex << std::setfill('0') << std::setw(2)
                << (int)instr.src.value.imm8 << std::dec << ";\n";
            out << "nes6502_set_nz(ctx, ctx->a);\n";
            break;

        case ir::Opcode::LOAD_X_IMM:
            out << "ctx->x = 0x" << std::hex << std::setfill('0') << std::setw(2)
                << (int)instr.src.value.imm8 << std::dec << ";\n";
            out << "nes6502_set_nz(ctx, ctx->x);\n";
            break;

        case ir::Opcode::LOAD_Y_IMM:
            out << "ctx->y = 0x" << std::hex << std::setfill('0') << std::setw(2)
                << (int)instr.src.value.imm8 << std::dec << ";\n";
            out << "nes6502_set_nz(ctx, ctx->y);\n";
            break;

        // === Data Movement - Load from Memory ===
        case ir::Opcode::LOAD_A_ADDR:
            out << "ctx->a = nes_read8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.src.value.imm16 << std::dec << ");\n";
            out << "nes6502_set_nz(ctx, ctx->a);\n";
            break;

        case ir::Opcode::LOAD_A_X:
            out << "ctx->a = nes_read8(ctx, (0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.src.value.imm16 << std::dec << " + ctx->x) & 0xFFFF);\n";
            out << "nes6502_set_nz(ctx, ctx->a);\n";
            break;

        case ir::Opcode::LOAD_A_Y:
            out << "ctx->a = nes_read8(ctx, (0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.src.value.imm16 << std::dec << " + ctx->y) & 0xFFFF);\n";
            out << "nes6502_set_nz(ctx, ctx->a);\n";
            break;

        case ir::Opcode::LOAD_A_IND_X: {
            uint8_t zp_addr = instr.src.value.imm8;
            out << "{\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "uint8_t zp_addr = (0x" << std::hex << std::setfill('0') << std::setw(2)
                << (int)zp_addr << std::dec << " + ctx->x) & 0xFF;\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "uint16_t ptr = nes_read16(ctx, zp_addr);\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "ctx->a = nes_read8(ctx, ptr);\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "nes6502_set_nz(ctx, ctx->a);\n";
            for (int i = 0; i < indent; i++) out << "    ";
            out << "}\n";
            break;
        }

        case ir::Opcode::LOAD_A_IND_Y: {
            uint8_t zp_addr = instr.src.value.imm8;
            out << "{\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "uint16_t ptr = nes_read16(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(2) << (int)zp_addr << std::dec << ");\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "ctx->a = nes_read8(ctx, (ptr + ctx->y) & 0xFFFF);\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "nes6502_set_nz(ctx, ctx->a);\n";
            for (int i = 0; i < indent; i++) out << "    ";
            out << "}\n";
            break;
        }

        case ir::Opcode::LOAD_X_ADDR:
            out << "ctx->x = nes_read8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.src.value.imm16 << std::dec << ");\n";
            out << "nes6502_set_nz(ctx, ctx->x);\n";
            break;

        case ir::Opcode::LOAD_Y_ADDR:
            out << "ctx->y = nes_read8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.src.value.imm16 << std::dec << ");\n";
            out << "nes6502_set_nz(ctx, ctx->y);\n";
            break;

        // === Data Movement - Store to Memory ===
        case ir::Opcode::STORE_A_ADDR:
            out << "nes_write8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.dst.value.imm16 << std::dec << ", ctx->a);\n";
            break;

        case ir::Opcode::STORE_A_X:
            out << "nes_write8(ctx, (0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.dst.value.imm16 << std::dec << " + ctx->x) & 0xFFFF, ctx->a);\n";
            break;

        case ir::Opcode::STORE_A_Y:
            out << "nes_write8(ctx, (0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.dst.value.imm16 << std::dec << " + ctx->y) & 0xFFFF, ctx->a);\n";
            break;

        case ir::Opcode::STORE_A_IND_X: {
            uint8_t zp_addr = instr.dst.value.imm8;
            out << "{\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "uint8_t zp_addr = (0x" << std::hex << std::setfill('0') << std::setw(2)
                << (int)zp_addr << std::dec << " + ctx->x) & 0xFF;\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "uint16_t ptr = nes_read16(ctx, zp_addr);\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "nes_write8(ctx, ptr, ctx->a);\n";
            for (int i = 0; i < indent; i++) out << "    ";
            out << "}\n";
            break;
        }

        case ir::Opcode::STORE_A_IND_Y: {
            uint8_t zp_addr = instr.dst.value.imm8;
            out << "{\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "uint16_t ptr = nes_read16(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(2) << (int)zp_addr << std::dec << ");\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "nes_write8(ctx, (ptr + ctx->y) & 0xFFFF, ctx->a);\n";
            for (int i = 0; i < indent; i++) out << "    ";
            out << "}\n";
            break;
        }

        case ir::Opcode::STORE_X_ADDR:
            out << "nes_write8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.dst.value.imm16 << std::dec << ", ctx->x);\n";
            break;

        case ir::Opcode::STORE_Y_ADDR:
            out << "nes_write8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << instr.dst.value.imm16 << std::dec << ", ctx->y);\n";
            break;

        // === Data Movement - Transfer ===
        case ir::Opcode::TRANSFER_A_X:
            out << "ctx->x = ctx->a;\n";
            out << "nes6502_set_nz(ctx, ctx->x);\n";
            break;

        case ir::Opcode::TRANSFER_A_Y:
            out << "ctx->y = ctx->a;\n";
            out << "nes6502_set_nz(ctx, ctx->y);\n";
            break;

        case ir::Opcode::TRANSFER_X_A:
            out << "ctx->a = ctx->x;\n";
            out << "nes6502_set_nz(ctx, ctx->a);\n";
            break;

        case ir::Opcode::TRANSFER_Y_A:
            out << "ctx->a = ctx->y;\n";
            out << "nes6502_set_nz(ctx, ctx->a);\n";
            break;

        case ir::Opcode::TRANSFER_X_SP:
            out << "ctx->sp = ctx->x;\n";
            break;

        case ir::Opcode::TRANSFER_SP_X:
            out << "ctx->x = ctx->sp;\n";
            out << "nes6502_set_nz(ctx, ctx->x);\n";
            break;

        // === Data Movement - Stack ===
        case ir::Opcode::PUSH_A:
            out << "nes_push8(ctx, ctx->a);\n";
            break;

        case ir::Opcode::PUSH_SR:
            out << "nes_push8(ctx, nes6502_get_sr(ctx));\n";
            break;

        case ir::Opcode::PULL_A:
            out << "ctx->a = nes_pop8(ctx);\n";
            out << "nes6502_set_nz(ctx, ctx->a);\n";
            break;

        case ir::Opcode::PULL_SR:
            out << "nes6502_set_sr(ctx, nes_pop8(ctx));\n";
            break;

        // === ALU - Arithmetic ===
        case ir::Opcode::ADC:
            if (instr.src.type == ir::OperandType::IMM8) {
                out << "nes6502_adc(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.src.value.imm8 << std::dec << ");\n";
            } else if (instr.src.type == ir::OperandType::REG8) {
                const char* reg = get_reg8_6502_name(instr.src.value.reg8);
                out << "nes6502_adc(ctx, ctx->" << (reg ? reg : "a") << ");\n";
            } else {
                out << "/* ADC from memory - operand type " << (int)instr.src.type << " */\n";
            }
            break;

        case ir::Opcode::SBC:
            if (instr.src.type == ir::OperandType::IMM8) {
                out << "nes6502_sbc(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.src.value.imm8 << std::dec << ");\n";
            } else if (instr.src.type == ir::OperandType::REG8) {
                const char* reg = get_reg8_6502_name(instr.src.value.reg8);
                out << "nes6502_sbc(ctx, ctx->" << (reg ? reg : "a") << ");\n";
            } else {
                out << "/* SBC from memory - operand type " << (int)instr.src.type << " */\n";
            }
            break;

        // === ALU - Logical ===
        case ir::Opcode::AND:
            if (instr.src.type == ir::OperandType::IMM8) {
                out << "nes6502_and(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.src.value.imm8 << std::dec << ");\n";
            } else if (instr.src.type == ir::OperandType::REG8) {
                const char* reg = get_reg8_6502_name(instr.src.value.reg8);
                out << "nes6502_and(ctx, ctx->" << (reg ? reg : "a") << ");\n";
            } else {
                out << "/* AND from memory - operand type " << (int)instr.src.type << " */\n";
            }
            break;

        case ir::Opcode::ORA:
            if (instr.src.type == ir::OperandType::IMM8) {
                out << "nes6502_ora(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.src.value.imm8 << std::dec << ");\n";
            } else if (instr.src.type == ir::OperandType::REG8) {
                const char* reg = get_reg8_6502_name(instr.src.value.reg8);
                out << "nes6502_ora(ctx, ctx->" << (reg ? reg : "a") << ");\n";
            } else {
                out << "/* ORA from memory - operand type " << (int)instr.src.type << " */\n";
            }
            break;

        case ir::Opcode::EOR:
            if (instr.src.type == ir::OperandType::IMM8) {
                out << "nes6502_eor(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.src.value.imm8 << std::dec << ");\n";
            } else if (instr.src.type == ir::OperandType::REG8) {
                const char* reg = get_reg8_6502_name(instr.src.value.reg8);
                out << "nes6502_eor(ctx, ctx->" << (reg ? reg : "a") << ");\n";
            } else {
                out << "/* EOR from memory - operand type " << (int)instr.src.type << " */\n";
            }
            break;

        case ir::Opcode::BIT:
            if (instr.src.type == ir::OperandType::IMM8) {
                out << "nes6502_bit(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.src.value.imm8 << std::dec << ");\n";
            } else if (instr.src.type == ir::OperandType::REG8) {
                const char* reg = get_reg8_6502_name(instr.src.value.reg8);
                out << "nes6502_bit(ctx, ctx->" << (reg ? reg : "a") << ");\n";
            } else {
                // Memory operand - need to read from memory first
                out << "{\n";
                for (int i = 0; i < indent + 1; i++) out << "    ";
                out << "uint8_t val;\n";
                
                // Generate memory read based on operand type
                switch (instr.src.type) {
                    case ir::OperandType::MEM_IMM16:
                    case ir::OperandType::ADDR:
                        for (int i = 0; i < indent + 1; i++) out << "    ";
                        out << "val = nes_read8(ctx, 0x" << std::hex << std::setfill('0') << std::setw(4)
                            << instr.src.value.imm16 << std::dec << ");\n";
                        break;
                    case ir::OperandType::MEM_ZPG:
                        for (int i = 0; i < indent + 1; i++) out << "    ";
                        out << "val = nes_read8(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                            << (int)instr.src.value.imm8 << std::dec << ");\n";
                        break;
                    case ir::OperandType::MEM_ZPG_X:
                        for (int i = 0; i < indent + 1; i++) out << "    ";
                        out << "val = nes_read8(ctx, (0x" << std::hex << std::setfill('0') << std::setw(2)
                            << (int)instr.src.value.imm8 << std::dec << " + ctx->x) & 0xFF);\n";
                        break;
                    case ir::OperandType::MEM_ZPG_Y:
                        for (int i = 0; i < indent + 1; i++) out << "    ";
                        out << "val = nes_read8(ctx, (0x" << std::hex << std::setfill('0') << std::setw(2)
                            << (int)instr.src.value.imm8 << std::dec << " + ctx->y) & 0xFF);\n";
                        break;
                    case ir::OperandType::MEM_ABS_X:
                        for (int i = 0; i < indent + 1; i++) out << "    ";
                        out << "val = nes_read8(ctx, (0x" << std::hex << std::setfill('0') << std::setw(4)
                            << instr.src.value.imm16 << std::dec << " + ctx->x) & 0xFFFF);\n";
                        break;
                    case ir::OperandType::MEM_ABS_Y:
                        for (int i = 0; i < indent + 1; i++) out << "    ";
                        out << "val = nes_read8(ctx, (0x" << std::hex << std::setfill('0') << std::setw(4)
                            << instr.src.value.imm16 << std::dec << " + ctx->y) & 0xFFFF);\n";
                        break;
                    default:
                        for (int i = 0; i < indent + 1; i++) out << "    ";
                        out << "/* Unknown BIT addressing mode " << (int)instr.src.type << " */\n";
                        for (int i = 0; i < indent + 1; i++) out << "    ";
                        out << "val = 0x00;\n";
                        break;
                }
                
                for (int i = 0; i < indent + 1; i++) out << "    ";
                out << "nes6502_bit(ctx, val);\n";
                for (int i = 0; i < indent; i++) out << "    ";
                out << "}\n";
            }
            break;

        // === ALU - Compare ===
        case ir::Opcode::CMP:
            if (instr.src.type == ir::OperandType::IMM8) {
                out << "nes6502_cmp(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.src.value.imm8 << std::dec << ");\n";
            } else if (instr.src.type == ir::OperandType::REG8) {
                const char* reg = get_reg8_6502_name(instr.src.value.reg8);
                out << "nes6502_cmp(ctx, ctx->" << (reg ? reg : "a") << ");\n";
            } else {
                out << "/* CMP from memory - operand type " << (int)instr.src.type << " */\n";
            }
            break;

        case ir::Opcode::CPX:
            if (instr.src.type == ir::OperandType::IMM8) {
                out << "nes6502_cpx(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.src.value.imm8 << std::dec << ");\n";
            } else if (instr.src.type == ir::OperandType::REG8) {
                const char* reg = get_reg8_6502_name(instr.src.value.reg8);
                out << "nes6502_cpx(ctx, ctx->" << (reg ? reg : "a") << ");\n";
            } else {
                out << "/* CPX from memory - operand type " << (int)instr.src.type << " */\n";
            }
            break;

        case ir::Opcode::CPY:
            if (instr.src.type == ir::OperandType::IMM8) {
                out << "nes6502_cpy(ctx, 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.src.value.imm8 << std::dec << ");\n";
            } else if (instr.src.type == ir::OperandType::REG8) {
                const char* reg = get_reg8_6502_name(instr.src.value.reg8);
                out << "nes6502_cpy(ctx, ctx->" << (reg ? reg : "a") << ");\n";
            } else {
                out << "/* CPY from memory - operand type " << (int)instr.src.type << " */\n";
            }
            break;

        // === ALU - Shift/Rotate ===
        case ir::Opcode::ASL:
            out << "nes6502_asl(ctx, &ctx->a);\n";
            break;

        case ir::Opcode::LSR:
            out << "nes6502_lsr(ctx, &ctx->a);\n";
            break;

        case ir::Opcode::ROL:
            out << "nes6502_rol(ctx, &ctx->a);\n";
            break;

        case ir::Opcode::ROR:
            out << "nes6502_ror(ctx, &ctx->a);\n";
            break;

        // === ALU - Increment/Decrement ===
        case ir::Opcode::INC_A:
            out << "ctx->a = nes_inc8(ctx, ctx->a);\n";
            break;

        case ir::Opcode::INC: {
            // INC memory - read-modify-write
            uint16_t addr = instr.dst.value.imm16;
            out << "{\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "uint8_t val = nes_read8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << addr << std::dec << ");\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "val = nes_inc8(ctx, val);\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "nes_write8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << addr << std::dec << ", val);\n";
            for (int i = 0; i < indent; i++) out << "    ";
            out << "}\n";
            break;
        }

        case ir::Opcode::DEC_A:
            out << "ctx->a = nes_dec8(ctx, ctx->a);\n";
            break;

        case ir::Opcode::DEC: {
            // DEC memory - read-modify-write
            uint16_t addr = instr.dst.value.imm16;
            out << "{\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "uint8_t val = nes_read8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << addr << std::dec << ");\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "val = nes_dec8(ctx, val);\n";
            for (int i = 0; i < indent + 1; i++) out << "    ";
            out << "nes_write8(ctx, 0x" << std::hex << std::setfill('0')
                << std::setw(4) << addr << std::dec << ", val);\n";
            for (int i = 0; i < indent; i++) out << "    ";
            out << "}\n";
            break;
        }

        case ir::Opcode::INC_X:
            out << "ctx->x = nes_inc8(ctx, ctx->x);\n";
            break;

        case ir::Opcode::DEC_X:
            out << "ctx->x = nes_dec8(ctx, ctx->x);\n";
            break;

        case ir::Opcode::INC_Y:
            out << "ctx->y = nes_inc8(ctx, ctx->y);\n";
            break;

        case ir::Opcode::DEC_Y:
            out << "ctx->y = nes_dec8(ctx, ctx->y);\n";
            break;

        // === Control Flow - Jumps ===
        case ir::Opcode::JMP_ABS: {
            uint16_t target = instr.dst.value.imm16;
            uint8_t tbank = instr.dst.bank;

            if (tbank == 255) {
                if (options.emit_cycle_counting && instr.cycles > 0) {
                    out << "nes_tick(ctx, " << (int)instr.cycles << ");\n";
                    emit_indent();
                }
                out << "ctx->pc = 0x" << std::hex << std::setfill('0')
                    << std::setw(4) << target << std::dec << "; return;\n";
            } else {
                std::string target_func = program.make_function_name(tbank, target);
                bool func_exists = program.functions.find(target_func) != program.functions.end();

                if (func_exists && target_func == current_func_name) {
                    if (options.emit_cycle_counting && group_cycles > 0) {
                        out << "ctx->pc = 0x" << std::hex << target << std::dec << ";\n";
                        emit_indent();
                        out << "nes_tick(ctx, " << (int)group_cycles << ");\n";
                        emit_indent();
                        out << "if (ctx->stopped) return;\n";
                    } else {
                        out << "ctx->pc = 0x" << std::hex << target << std::dec << ";\n";
                    }
                    emit_indent();
                    out << "goto loc_" << std::hex << std::setfill('0')
                        << std::setw(4) << target << std::dec << ";\n";
                } else if (func_exists) {
                    if (options.emit_cycle_counting && instr.cycles > 0) {
                        out << "nes_tick(ctx, " << (int)instr.cycles << ");\n";
                        emit_indent();
                    }
                    out << "ctx->pc = 0x" << std::hex << target << std::dec << ";\n";
                    emit_indent();
                    out << target_func << "(ctx);\n";
                    emit_indent();
                    out << "return;\n";
                } else {
                    if (options.emit_cycle_counting && instr.cycles > 0) {
                        out << "nes_tick(ctx, " << (int)instr.cycles << ");\n";
                        emit_indent();
                    }
                    out << "ctx->pc = 0x" << std::hex << std::setfill('0')
                        << std::setw(4) << target << std::dec << "; return;\n";
                }
            }
            break;
        }

        case ir::Opcode::JMP_IND:
            out << "nesrt_jump_hl(ctx);\n";
            if (options.emit_cycle_counting && group_cycles > 0) {
                emit_indent();
                out << "nes_tick(ctx, " << (int)group_cycles << ");\n";
                emit_indent();
                out << "if (ctx->stopped) return;\n";
            }
            emit_indent();
            out << "return;\n";
            break;

        // === Control Flow - Subroutine ===
        case ir::Opcode::JSR: {
            uint16_t target = instr.dst.value.imm16;
            uint8_t target_bank = instr.dst.bank;
            // 6502 JSR pushes (PC - 1), where PC is the address after the JSR
            // JSR is 3 bytes, so PC after = source + 3, pushed value = source + 2
            uint16_t return_addr = instr.source_address + 2;

            if (target_bank == 255) {
                out << "nes_push16(ctx, 0x" << std::hex << return_addr << std::dec << ");\n";
                emit_indent();
                // Trace push before call
                out << "#ifdef NESRT_TRACE_ENABLED\n";
                emit_indent();
                out << "nesrt_trace_push(0x" << std::hex << target << std::dec << ");\n";
                emit_indent();
                out << "#endif\n";
                emit_indent();
                out << "ctx->pc = 0x" << std::hex << target << std::dec << ";\n";
                if (options.emit_cycle_counting && group_cycles > 0) {
                    emit_indent();
                    out << "nes_tick(ctx, " << (int)group_cycles << ");\n";
                    emit_indent();
                    out << "if (ctx->stopped) return;\n";
                }
                emit_indent();
                out << "return;\n";
            } else {
                std::string func_name = program.make_function_name(target_bank, target);
                bool func_exists = program.functions.find(func_name) != program.functions.end();

                out << "nes_push16(ctx, 0x" << std::hex << return_addr << std::dec << ");\n";
                emit_indent();
                // Trace push before call
                out << "#ifdef NESRT_TRACE_ENABLED\n";
                emit_indent();
                out << "nesrt_trace_push(0x" << std::hex << target << std::dec << ");\n";
                emit_indent();
                out << "#endif\n";
                emit_indent();
                out << "ctx->pc = 0x" << std::hex << target << std::dec << ";\n";
                if (options.emit_cycle_counting && group_cycles > 0) {
                    emit_indent();
                    out << "nes_tick(ctx, " << (int)group_cycles << ");\n";
                    emit_indent();
                    out << "if (ctx->stopped) return;\n";
                }
                emit_indent();
                if (func_exists) {
                    out << func_name << "(ctx);\n";
                    emit_indent();
                    // Trace pop after return
                    out << "#ifdef NESRT_TRACE_ENABLED\n";
                    emit_indent();
                    out << "nesrt_trace_pop();\n";
                    emit_indent();
                    out << "#endif\n";
                    emit_indent();
                    out << "if (ctx->pc != 0x" << std::hex << target << std::dec << ") return; /* RTS modified PC */\n";
                }
                emit_indent();
                out << "return;\n";
            }
            break;
        }

        case ir::Opcode::RTS:
            // Trace pop on RTS
            out << "#ifdef NESRT_TRACE_ENABLED\n";
            emit_indent();
            out << "nesrt_trace_pop();\n";
            emit_indent();
            out << "#endif\n";
            emit_indent();
            out << "ctx->pc = nes_pop16(ctx) + 1;\n";
            emit_indent();
            out << "return;\n";
            if (options.emit_cycle_counting && group_cycles > 0) {
                emit_indent();
                out << "nes_tick(ctx, " << (int)group_cycles << ");\n";
            }
            break;

        case ir::Opcode::RTI:
            out << "ctx->f_i = 0;  /* Clear interrupt disable */\n";
            emit_indent();
            out << "return;\n";
            if (options.emit_cycle_counting && group_cycles > 0) {
                emit_indent();
                out << "nes_tick(ctx, " << (int)group_cycles << ");\n";
            }
            break;

        // === Control Flow - Branches ===
        case ir::Opcode::BCC:
        case ir::Opcode::BCS:
        case ir::Opcode::BEQ:
        case ir::Opcode::BNE:
        case ir::Opcode::BMI:
        case ir::Opcode::BPL:
        case ir::Opcode::BVC:
        case ir::Opcode::BVS: {
            uint16_t target = instr.dst.value.imm16;
            uint8_t tbank = instr.dst.bank;
            const char* cond = cond_6502_names[instr.src.value.condition];
            const char* expr = get_cond_expr_6502(instr.src.value.condition);

            if (tbank == 255) {
                out << "if (" << expr << ") {\n";
                emit_indent();
                out << "    ctx->pc = 0x" << std::hex << target << std::dec << ";\n";
                if (options.emit_cycle_counting) {
                    emit_indent();
                    out << "    nes_tick(ctx, " << (int)instr.cycles_branch_taken << ");\n";
                    emit_indent();
                    out << "    if (ctx->stopped) return;\n";
                }
                emit_indent();
                out << "    return;\n";
                emit_indent();
                out << "} /* " << cond << " */\n";
            } else {
                std::string target_func = program.make_function_name(tbank, target);
                bool func_exists = program.functions.find(target_func) != program.functions.end();

                if (func_exists && target_func == current_func_name) {
                    out << "if (" << expr << ") {\n";
                    emit_indent();
                    out << "    ctx->pc = 0x" << std::hex << target << std::dec << ";\n";
                    if (options.emit_cycle_counting) {
                        emit_indent();
                        out << "    nes_tick(ctx, " << (int)instr.cycles_branch_taken << ");\n";
                        emit_indent();
                        out << "    if (ctx->stopped) return;\n";
                    }
                    emit_indent();
                    out << "    goto loc_" << std::hex << std::setfill('0')
                        << std::setw(4) << target << std::dec << ";\n";
                    emit_indent();
                    out << "} /* " << cond << " */\n";
                } else if (func_exists) {
                    out << "if (" << expr << ") {\n";
                    emit_indent();
                    out << "    ctx->pc = 0x" << std::hex << target << std::dec << ";\n";
                    if (options.emit_cycle_counting) {
                        emit_indent();
                        out << "    nes_tick(ctx, " << (int)instr.cycles_branch_taken << ");\n";
                        emit_indent();
                        out << "    if (ctx->stopped) return;\n";
                    }
                    emit_indent();
                    out << "    " << target_func << "(ctx);\n";
                    emit_indent();
                    out << "    return;\n";
                    emit_indent();
                    out << "} /* " << cond << " */\n";
                } else {
                    out << "if (" << expr << ") {\n";
                    emit_indent();
                    out << "    ctx->pc = 0x" << std::hex << target << std::dec << ";\n";
                    if (options.emit_cycle_counting) {
                        emit_indent();
                        out << "    nes_tick(ctx, " << (int)instr.cycles_branch_taken << ");\n";
                        emit_indent();
                        out << "    if (ctx->stopped) return;\n";
                    }
                    emit_indent();
                    out << "    return;\n";
                    emit_indent();
                    out << "} /* " << cond << " */\n";
                }
            }
            // Branch NOT taken - use instr.cycles (2 cycles) not group_cycles
            if (next_pc_val != 0) {
                emit_indent();
                out << "ctx->pc = 0x" << std::hex << next_pc_val << std::dec << ";\n";
            }
            if (options.emit_cycle_counting && instr.cycles > 0) {
                emit_indent();
                out << "nes_tick(ctx, " << (int)instr.cycles << ");\n";
                emit_indent();
                out << "if (ctx->stopped) return;\n";
            }
            break;
        }

        // === Control Flow - Special ===
        case ir::Opcode::BRK:
            {
                uint16_t next_pc = instr.source_address + 1;
                out << "nes_push16(ctx, 0x" << std::hex << next_pc << std::dec << ");\n";
                emit_indent();
                out << "ctx->pc = 0x" << std::hex << std::setfill('0') << std::setw(2)
                    << (int)instr.dst.value.imm8 << std::dec << ";\n";
                if (options.emit_cycle_counting && group_cycles > 0) {
                    emit_indent();
                    out << "nes_tick(ctx, " << (int)group_cycles << ");\n";
                    emit_indent();
                    out << "if (ctx->stopped) return;\n";
                }
                emit_indent();
                out << "return;\n";
            }
            break;

        // === Flag Control ===
        case ir::Opcode::CLC:
            out << "ctx->f_c = 0;\n";
            break;

        case ir::Opcode::SEC:
            out << "ctx->f_c = 1;\n";
            break;

        case ir::Opcode::CLI:
            out << "ctx->f_i = 0;\n";
            break;

        case ir::Opcode::SEI:
            out << "ctx->f_i = 1;\n";
            break;

        case ir::Opcode::CLD:
            out << "ctx->f_d = 0;\n";
            break;

        case ir::Opcode::SED:
            out << "ctx->f_d = 1;\n";
            break;

        case ir::Opcode::CLV:
            out << "ctx->f_v = 0;\n";
            break;

        // === Meta ===
        case ir::Opcode::LABEL:
            out << "loc_" << std::hex << std::setfill('0') << std::setw(4)
                << instr.dst.value.imm16 << std::dec << ":\n";
            break;

        case ir::Opcode::COMMENT:
            out << "/* " << instr.comment << " */\n";
            break;

        case ir::Opcode::SOURCE_LOC:
            // Already handled at the top
            break;

        default:
            out << "/* Unhandled opcode: " << (int)instr.opcode << " */\n";
            break;
    }

    // Emit cycle counting and PC update at block boundaries
    bool is_control_flow = (instr.opcode == ir::Opcode::RTS ||
                            instr.opcode == ir::Opcode::RTI ||
                            instr.opcode == ir::Opcode::JMP_ABS ||
                            instr.opcode == ir::Opcode::JMP_IND ||
                            instr.opcode == ir::Opcode::JSR ||
                            instr.opcode == ir::Opcode::BCC ||
                            instr.opcode == ir::Opcode::BCS ||
                            instr.opcode == ir::Opcode::BEQ ||
                            instr.opcode == ir::Opcode::BNE ||
                            instr.opcode == ir::Opcode::BMI ||
                            instr.opcode == ir::Opcode::BPL ||
                            instr.opcode == ir::Opcode::BVC ||
                            instr.opcode == ir::Opcode::BVS ||
                            instr.opcode == ir::Opcode::BRK);

    if (is_last_in_group && !is_control_flow) {
        if (next_pc_val != 0) {
            emit_indent();
            out << "ctx->pc = 0x" << std::hex << next_pc_val << std::dec << ";\n";
        }

        if (options.emit_cycle_counting && group_cycles > 0) {
            emit_indent();
            out << "nes_tick(ctx, " << (int)group_cycles << ");\n";
            emit_indent();
            out << "if (ctx->stopped) return;\n";
        }
    }
}

GeneratedOutput generate_output(const ir::Program& program,
                                const uint8_t* rom_data,
                                size_t rom_size,
                                const GeneratorOptions& options) {
    GeneratedOutput output;
    
    // Generate header
    std::ostringstream header_ss;
    header_ss << "/* Generated by nesrecomp */\n";
    header_ss << "#ifndef " << options.output_prefix << "_H\n";
    header_ss << "#define " << options.output_prefix << "_H\n\n";
    header_ss << "#include \"nesrt.h\"\n\n";
    header_ss << "void " << options.output_prefix << "_run(NESContext* ctx);\n";
    header_ss << "void " << options.output_prefix << "_init(NESContext* ctx);\n\n";
    header_ss << "#endif\n";
    output.header_content = header_ss.str();
    output.header_file = options.output_prefix + ".h";
    
    // Generate source
    std::ostringstream source_ss;
    source_ss << "/* Generated by nesrecomp from " << program.rom_name << " */\n";
    source_ss << "#include \"" << options.output_prefix << ".h\"\n";
    source_ss << "#include \"nesrt.h\"\n";
    source_ss << "#ifdef NESRT_TRACE_ENABLED\n";
    source_ss << "#include \"nesrt_trace.h\"\n";
    source_ss << "#endif\n";
    source_ss << "#include <stdio.h>\n";
    source_ss << "#include <stdlib.h>\n\n";
    
    // Forward declarations
    source_ss << "/* Forward declarations */\n";
    for (const auto& [name, func] : program.functions) {
        source_ss << "static void " << func.name << "(NESContext* ctx);\n";
    }
    source_ss << "\n";
    
    // Generate dispatch function for banked calls
    source_ss << "/* Dispatch - routes calls to the correct function */\n";
    source_ss << "void nes_dispatch(NESContext* ctx, uint16_t addr) {\n";
    source_ss << "    ctx->pc = addr;\n";
    source_ss << "    while (!ctx->stopped) {\n";
    source_ss << "        addr = ctx->pc;\n";

    /* Debug checks in dispatch loop */
    source_ss << "        if (nesrt_instruction_limit > 0 && nesrt_instruction_count >= nesrt_instruction_limit) {\n";
    source_ss << "            fprintf(stderr, \"[LIMIT] Reached instruction limit %llu\\n\", (unsigned long long)nesrt_instruction_limit);\n";
    source_ss << "            exit(0);\n";
    source_ss << "        }\n";
    source_ss << "        nesrt_instruction_count++;\n";
    source_ss << "        \n";
    source_ss << "        if (nesrt_trace_enabled) {\n";
    source_ss << "            fprintf(stderr, \"[TRACE] Dispatch 0x%04X\\n\", addr);\n";
    source_ss << "        }\n";
    source_ss << "        nesrt_log_trace(ctx, 0, addr);\n";

    source_ss << "        switch (addr) {\n";
    
    // Identify inlineable functions
    // A function can be inlined if:
    // - It has a single basic block
    // - It's small (<= 25 instructions)
    // - It ends with RTS
    // - It doesn't contain JSR/JMP/RTS/RTI/BRK in the middle
    // - It's not an interrupt handler or entry point
    // - It's NOT called from other functions (only through dispatch)
    std::set<std::string> inlineable_functions;

    // First, find all functions that are called from other functions
    std::set<std::string> called_functions;
    for (const auto& [block_id, block] : program.blocks) {
        for (const auto& instr : block.instructions) {
            if (instr.opcode == ir::Opcode::JSR) {
                uint16_t target = instr.dst.value.imm16;
                uint8_t target_bank = instr.dst.bank;
                std::string target_func = program.make_function_name(target_bank, target);
                called_functions.insert(target_func);
            }
        }
    }
    
    // For MMC1, only include functions in bank 0 or the last bank (fixed region)
    uint8_t last_bank = 0;
    for (const auto& [name, func] : program.functions) {
        if (func.bank > last_bank) last_bank = func.bank;
    }

    for (const auto& [name, func] : program.functions) {
        // Skip functions in intermediate banks (MMC1 switching makes these unreliable)
        if (func.bank > 0 && func.bank < last_bank) continue;
        
        if (func.block_ids.size() != 1) continue;
        const auto& block = program.blocks.at(func.block_ids[0]);
        if (block.instructions.size() > 25) continue;
        if (block.instructions.empty()) continue;
        const auto& last = block.instructions.back();
        if (last.opcode != ir::Opcode::RTS) continue;

        bool safe_to_inline = true;
        for (size_t i = 0; i < block.instructions.size() - 1; i++) {
             const auto& op = block.instructions[i].opcode;
             if (op == ir::Opcode::JMP_ABS || op == ir::Opcode::JSR ||
                 op == ir::Opcode::RTS || op == ir::Opcode::RTI || op == ir::Opcode::BRK) {
                 safe_to_inline = false;
                 break;
             }
        }
        if (!safe_to_inline) continue;
        if (func.is_interrupt_handler || func.is_entry_point) continue;
        // Don't inline functions that are called from other functions
        if (called_functions.count(name)) continue;
        inlineable_functions.insert(func.name);
    }
    
    // Group functions by address for the switch statement
    struct DispatchEntry {
        std::string name;
        bool is_entry;
        bool operator<(const DispatchEntry& o) const {
            if (is_entry != o.is_entry) return is_entry > o.is_entry;
            return name < o.name;
        }
        bool operator==(const DispatchEntry& o) const {
            return name == o.name && is_entry == o.is_entry;
        }
    };
    std::map<uint16_t, std::vector<DispatchEntry>> addr_to_funcs;

    // Add function entry points
    for (const auto& [name, func] : program.functions) {
        addr_to_funcs[func.entry_address].push_back({func.name, true});
    }

    // Add all basic block addresses (non-entry blocks need to call their containing function)
    // The function's internal switch will route to the correct block via computed goto
    // For MMC1, only include functions in bank 0 or the last bank (fixed region)
    for (const auto& [name, func] : program.functions) {
        // Skip functions in intermediate banks (MMC1 switching makes these unreliable)
        if (func.bank > 0 && func.bank < last_bank) continue;
        
        // Skip functions that won't have definitions (no valid blocks)
        if (func.block_ids.empty()) continue;
        bool has_valid_blocks = false;
        for (uint32_t block_id : func.block_ids) {
            auto it = program.blocks.find(block_id);
            if (it != program.blocks.end() && !it->second.instructions.empty()) {
                has_valid_blocks = true;
                break;
            }
        }
        if (!has_valid_blocks) continue;
        
        for (uint32_t block_id : func.block_ids) {
            auto it = program.blocks.find(block_id);
            if (it != program.blocks.end()) {
                uint16_t block_addr = it->second.start_address;
                // Don't add entry point twice - it's already added above
                if (block_addr != func.entry_address) {
                    addr_to_funcs[block_addr].push_back({func.name, false});
                }
            }
        }
    }

    for (auto& [addr, funcs] : addr_to_funcs) {
        std::sort(funcs.begin(), funcs.end());
        funcs.erase(std::unique(funcs.begin(), funcs.end()), funcs.end());

        source_ss << "            case 0x" << std::hex << std::setfill('0') << std::setw(4) << addr << std::dec << ":\n";

        if (funcs.size() == 1) {
            const auto& entry = funcs[0];
            // Only inline entry points, not mid-function blocks
            if (entry.is_entry && inlineable_functions.count(entry.name)) {
                source_ss << "                /* Inline: " << entry.name << " */ {\n";
                const auto& func = program.functions.at(entry.name);
                const auto& block = program.blocks.at(func.block_ids[0]);

                size_t limit = block.instructions.size();
                if (limit > 0 && block.instructions.back().opcode == ir::Opcode::RTS) limit--;

                uint32_t inline_cycles = 0;
                for (size_t k = 0; k < limit; k++) {
                    inline_cycles += block.instructions[k].cycles;
                    emit_ir_instruction(source_ss, block.instructions[k], program, 5, options, 0, 0, false, "", inlineable_functions);
                }
                if (block.instructions.size() > limit) inline_cycles += block.instructions.back().cycles;

                if (options.emit_cycle_counting) {
                     source_ss << "                    nes_tick(ctx, " << (int)inline_cycles << ");\n";
                     source_ss << "                    if (ctx->stopped) return;\n";
                }
                source_ss << "                } break;\n";
            } else {
                // Call the function - internal switch will route to correct block
                source_ss << "                " << entry.name << "(ctx); break;\n";
            }
        } else {
            source_ss << "                /* Multiple functions at same address - use first */\n";
            source_ss << "                " << funcs[0].name << "(ctx); break;\n";
        }
    }
    source_ss << "            default: nes_interpret(ctx, addr); break;\n";
    source_ss << "        }\n";
    source_ss << "    }\n";
    source_ss << "}\n\n";

    source_ss << "void nes_dispatch_call(NESContext* ctx, uint16_t addr) {\n";
    source_ss << "    nes_dispatch(ctx, addr);\n";
    source_ss << "}\n\n";
    
    // Emit each function with real IR code
    for (const auto& [name, func] : program.functions) {
        if (inlineable_functions.count(func.name)) {
            continue; // Skip inlined functions
        }
        source_ss << "/* Function at ";
        if (func.bank > 0) {
            source_ss << std::hex << std::setfill('0') << std::setw(2) << (int)func.bank << ":";
        }
        source_ss << std::hex << std::setfill('0') << std::setw(4) << func.entry_address << std::dec << " */\n";
        
        // Check if function has any blocks (may be missing due to bank switching)
        if (func.block_ids.empty()) {
            // Stub out function for missing bank code
            source_ss << "static void " << func.name << "(NESContext* ctx) {\n";
            source_ss << "    /* Stub: code in bank " << (int)func.bank << " not analyzed due to MMC1 banking */\n";
            source_ss << "    ctx->pc = 0x" << std::hex << std::setfill('0') << std::setw(4) << func.entry_address << std::dec << ";\n";
            source_ss << "    nes_interpret(ctx, ctx->pc);\n";
            source_ss << "}\n\n";
            continue;
        }
        
        // Check if blocks actually exist and have instructions
        bool has_valid_blocks = false;
        for (uint32_t block_id : func.block_ids) {
            auto it = program.blocks.find(block_id);
            if (it != program.blocks.end() && !it->second.instructions.empty()) {
                has_valid_blocks = true;
                break;
            }
        }
        if (!has_valid_blocks) {
            // Stub out function with empty/invalid blocks
            source_ss << "static void " << func.name << "(NESContext* ctx) {\n";
            source_ss << "    /* Stub: function in bank " << (int)func.bank << " has no valid IR blocks */\n";
            source_ss << "    ctx->pc = 0x" << std::hex << std::setfill('0') << std::setw(4) << func.entry_address << std::dec << ";\n";
            source_ss << "    nes_interpret(ctx, ctx->pc);\n";
            source_ss << "}\n\n";
            continue;
        }

        source_ss << "static void " << func.name << "(NESContext* ctx) {\n";

        // Trace push at function entry
        source_ss << "#ifdef NESRT_TRACE_ENABLED\n";
        source_ss << "    nesrt_trace_push(ctx->pc);\n";
        source_ss << "#endif\n";

        // Sort block_ids by their start address to ensure proper fallthrough order
        std::vector<uint32_t> sorted_block_ids = func.block_ids;
        std::sort(sorted_block_ids.begin(), sorted_block_ids.end(), 
            [&program](uint32_t a, uint32_t b) {
                auto it_a = program.blocks.find(a);
                auto it_b = program.blocks.find(b);
                if (it_a == program.blocks.end()) return false;
                if (it_b == program.blocks.end()) return true;
                return it_a->second.start_address < it_b->second.start_address;
            });
            
        // Emit computed goto for entry into the correct block
        source_ss << "    switch (ctx->pc) {\n";
        for (uint32_t block_id : sorted_block_ids) {
            auto it = program.blocks.find(block_id);
            if (it != program.blocks.end()) {
                source_ss << "        case 0x" << std::hex << std::setfill('0') << std::setw(4) 
                          << it->second.start_address << std::dec << ": goto loc_" 
                          << std::hex << std::setfill('0') << std::setw(4) 
                          << it->second.start_address << std::dec << ";\n";
            }
        }
        source_ss << "        default: break;\n";
        source_ss << "    }\n\n";
        
        // Emit each block in this function (now sorted by address)
        for (size_t block_idx = 0; block_idx < sorted_block_ids.size(); block_idx++) {
            uint32_t block_id = sorted_block_ids[block_idx];
            auto block_it = program.blocks.find(block_id);
            if (block_it == program.blocks.end()) continue;
            const ir::BasicBlock& block = block_it->second;
            
            // Generate label from block address
            source_ss << "loc_" << std::hex << std::setfill('0') << std::setw(4) 
                      << block.start_address << std::dec << ":\n";
            
            // Calculate total cycles for this basic block upfront (for batched counting)
            uint32_t block_total_cycles = 0;
            for (const auto& ir_instr : block.instructions) {
                block_total_cycles += ir_instr.cycles;
            }
            
            // Emit each IR instruction
            for (size_t i = 0; i < block.instructions.size(); ++i) {
                const auto& ir_instr = block.instructions[i];
                
                uint16_t next_pc = 0;
                bool is_last_in_block = (i + 1 >= block.instructions.size());
                
                // Calculate next PC
                if (i + 1 < block.instructions.size()) {
                    next_pc = block.instructions[i+1].source_address;
                } else {
                    next_pc = block.end_address;
                }
                
                // Only emit cycles at block boundaries (not per-instruction)
                // Pass total block cycles only for the last instruction
                uint32_t cycles_to_pass = is_last_in_block ? block_total_cycles : 0;
                
                emit_ir_instruction(source_ss, ir_instr, program, 1, options, next_pc, cycles_to_pass, is_last_in_block, func.name, inlineable_functions);
            }
            
            // Check if block falls through
            bool falls_through = true;
            uint16_t fallthrough_addr = block.end_address;
            
            // Find the last non-NOP instruction
            for (auto it = block.instructions.rbegin(); it != block.instructions.rend(); ++it) {
                if (it->opcode == ir::Opcode::NOP) continue;
                
                // Unconditional terminators do not fall through
                if (it->opcode == ir::Opcode::JMP_ABS || 
                    it->opcode == ir::Opcode::RTS) {
                    falls_through = false;
                }
                break;
            }
            
            bool next_is_fallthrough = false;
            if (block_idx + 1 < sorted_block_ids.size()) {
                uint32_t next_id = sorted_block_ids[block_idx + 1];
                auto next_it = program.blocks.find(next_id);
                if (next_it != program.blocks.end()) {
                    if (next_it->second.start_address == fallthrough_addr) {
                        next_is_fallthrough = true;
                    }
                }
            }
            
            if (falls_through && !next_is_fallthrough) {
                    // Debug specific function 27eb
                    if (func.name == "func_27eb") {
                        std::cerr << "DEBUG: found func_27eb falling through to 0x" << std::hex << fallthrough_addr << std::dec << "\n";
                    }

                    // Check if fallthrough target exists as a block in this function
                    bool fallthrough_exists_in_function = false;
                    for (uint32_t fn_block_id : sorted_block_ids) {
                        auto fn_block_it = program.blocks.find(fn_block_id);
                        if (fn_block_it != program.blocks.end() && 
                            fn_block_it->second.start_address == fallthrough_addr) {
                            fallthrough_exists_in_function = true;
                            break;
                        }
                    }
                    
                    // Only emit goto if the target block exists in this function
                    if (fallthrough_exists_in_function) {
                        // Emit explicit goto to fallthrough block
                        source_ss << "    goto loc_" << std::hex << std::setfill('0') 
                                  << std::setw(4) << fallthrough_addr << std::dec 
                                  << "; /* fallthrough */\n";
                    } else {
                        if (func.name == "func_27eb") {
                             std::cerr << "DEBUG: func_27eb fallthrough not in function. Searching targets...\n";
                        }
                        // Fallthrough to another function?
                        // Check if any function starts at fallthrough_addr in the same bank
                        bool found_target_func = false;
                        for (const auto& kv : program.functions) {
                            const ir::Function& target_func = kv.second;
                            if (target_func.bank == func.bank && target_func.entry_address == fallthrough_addr) {
                                source_ss << "    /* fallthrough to function */\n";
                                
                                if (inlineable_functions.count(target_func.name)) {
                                    source_ss << "    /* Inline: " << target_func.name << " */ {\n";
                                    const auto& block = program.blocks.at(target_func.block_ids[0]);

                                    size_t limit = block.instructions.size();
                                    if (limit > 0 && block.instructions.back().opcode == ir::Opcode::RTS) limit--;

                                    uint32_t inline_cycles = 0;
                                    for (size_t k = 0; k < limit; k++) {
                                        inline_cycles += block.instructions[k].cycles;
                                        emit_ir_instruction(source_ss, block.instructions[k], program, 2, options, 0, 0, false, "", inlineable_functions);
                                    }
                                    if (block.instructions.size() > limit) inline_cycles += block.instructions.back().cycles;

                                    if (options.emit_cycle_counting) {
                                         source_ss << "        nes_tick(ctx, " << (int)inline_cycles << ");\n";
                                         source_ss << "        if (ctx->stopped) return;\n";
                                    }
                                    source_ss << "    } /* End Inline */\n";
                                } else {
                                    source_ss << "    " << target_func.name << "(ctx);\n";
                                }
                                source_ss << "    return;\n";
                                found_target_func = true;
                                break;
                            }
                        }

                        if (!found_target_func) {
                            source_ss << "    /* warning: fallthrough to unanalyzed code at 0x"
                                      << std::hex << fallthrough_addr << std::dec << " */\n";
                            source_ss << "    return;\n";
                        }
                    }

            }
        }

        // Trace pop at function exit
        source_ss << "#ifdef NESRT_TRACE_ENABLED\n";
        source_ss << "    nesrt_trace_pop();\n";
        source_ss << "#endif\n";

        // If function is empty or has no terminator, add a return
        source_ss << "}\n\n";
    }
    
    // Extern reference to ROM data
    source_ss << "/* Extern reference to ROM data */\n";
    source_ss << "extern const uint8_t rom_data[];\n\n";

    // Emit init and run functions
    source_ss << "void " << options.output_prefix << "_init(NESContext* ctx) {\n";
    source_ss << "    /* Load ROM data into context */\n";
    source_ss << "    nes_context_load_rom(ctx, rom_data, " << rom_size << ");\n";
    source_ss << "}\n\n";

    source_ss << "void " << options.output_prefix << "_run(NESContext* ctx) {\n";
    source_ss << "    // Start the trampoline loop - execution will stay here until stopped\n";
    source_ss << "    nes_dispatch(ctx, ctx->pc);\n";
    source_ss << "}\n";
    
    output.source_content = source_ss.str();
    output.source_file = options.output_prefix + ".c";
    
    // Generate ROM data
    std::ostringstream rom_ss;
    rom_ss << "/* ROM data */\n";
    rom_ss << "#include <stdint.h>\n";
    rom_ss << "#include <stddef.h>\n\n";
    rom_ss << "const uint8_t rom_data[" << rom_size << "] = {\n";
    for (size_t i = 0; i < rom_size; i++) {
        if (i % 16 == 0) rom_ss << "    ";
        rom_ss << "0x" << std::hex << std::setfill('0') << std::setw(2) 
               << (int)rom_data[i];
        if (i < rom_size - 1) rom_ss << ",";
        if (i % 16 == 15 || i == rom_size - 1) rom_ss << "\n";
        else rom_ss << " ";
    }
    rom_ss << std::dec << "};\n";
    rom_ss << "const size_t rom_size = " << rom_size << ";\n";
    output.rom_data_content = rom_ss.str();
    output.rom_data_file = options.output_prefix + "_rom.c";
    
    // Generate main
    std::ostringstream main_ss;
    main_ss << "/* Main entry point */\n";
    main_ss << "#include \"" << options.output_prefix << ".h\"\n";
    main_ss << "#include \"nesrt.h\"\n";
    main_ss << "#ifdef NESRT_TRACE_ENABLED\n";
    main_ss << "#include \"nesrt_trace.h\"\n";
    main_ss << "#endif\n";
    main_ss << "#ifdef NES_HAS_SDL2\n";
    main_ss << "#include \"platform_sdl.h\"\n";
    main_ss << "#endif\n";
    main_ss << "#include <stdio.h>\n";
    main_ss << "#include <stdlib.h>\n";
    main_ss << "#include <string.h>\n\n";
    main_ss << "int main(int argc, char* argv[]) {\n";
    main_ss << "    // Parse global args (before context creation)\n";
    main_ss << "    for (int i = 1; i < argc; i++) {\n";
    main_ss << "        if (strcmp(argv[i], \"--trace\") == 0) {\n";
    main_ss << "            g_nesrt_trace.enabled = true;\n";
    main_ss << "            printf(\"Trace enabled\\n\");\n";
    main_ss << "        } else if (strcmp(argv[i], \"--trace-file\") == 0 && i + 1 < argc) {\n";
    main_ss << "            nesrt_trace_set_file(argv[++i]);\n";
    main_ss << "            printf(\"Trace file: %s\\n\", argv[i]);\n";
    main_ss << "        } else if (strcmp(argv[i], \"--trace-depth\") == 0 && i + 1 < argc) {\n";
    main_ss << "            nesrt_trace_set_max_depth(atoi(argv[++i]));\n";
    main_ss << "            printf(\"Trace depth: %d\\n\", nesrt_trace_get_max_depth());\n";
    main_ss << "        } else if (strcmp(argv[i], \"--trace-filter\") == 0 && i + 1 < argc) {\n";
    main_ss << "            nesrt_trace_set_tag_filter(argv[++i]);\n";
    main_ss << "            printf(\"Trace filter: %s\\n\", argv[i]);\n";
    main_ss << "        } else if (strcmp(argv[i], \"--trace-entries\") == 0 && i + 1 < argc) {\n";
    main_ss << "            nesrt_set_trace_file(argv[++i]);\n";
    main_ss << "        } else if (strcmp(argv[i], \"--limit\") == 0 && i + 1 < argc) {\n";
    main_ss << "            nesrt_instruction_limit = strtoull(argv[++i], NULL, 10);\n";
    main_ss << "            printf(\"Instruction limit: %llu\\n\", (unsigned long long)nesrt_instruction_limit);\n";
    main_ss << "        }\n";
    main_ss << "    }\n\n";
    main_ss << "    NESContext* ctx = nes_context_create(NULL);\n";
    main_ss << "    if (!ctx) {\n";
    main_ss << "        fprintf(stderr, \"Failed to create context\\n\");\n";
    main_ss << "        return 1;\n";
    main_ss << "    }\n\n";
    main_ss << "    // Parse context-dependent args\n";
    main_ss << "    for (int i = 1; i < argc; i++) {\n";
    main_ss << "        if (strcmp(argv[i], \"--no-debug\") == 0) {\n";
    main_ss << "            ctx->debug_port_enabled = false;\n";
    main_ss << "            printf(\"Debug port output disabled\\n\");\n";
    main_ss << "        } else if (strcmp(argv[i], \"--vsync\") == 0) {\n";
    main_ss << "            g_vsync = true;\n";
    main_ss << "            printf(\"VSync ENABLED (fixes compositor issues)\\n\");\n";
    main_ss << "        }\n";
    main_ss << "    }\n\n";
    main_ss << "    " << options.output_prefix << "_init(ctx);\n";
    main_ss << "\n";
    main_ss << "#ifdef NES_HAS_SDL2\n";
    main_ss << "    // Initialize SDL2 platform with 3x scaling\n";
    main_ss << "    if (!nes_platform_init(3)) {\n";
    main_ss << "        fprintf(stderr, \"Failed to initialize platform\\n\");\n";
    main_ss << "        nes_context_destroy(ctx);\n";
    main_ss << "        return 1;\n";
    main_ss << "    }\n";
    main_ss << "    nes_platform_register_context(ctx);\n";
    main_ss << "\n";
    main_ss << "    // Run the game loop\n";
    main_ss << "    while (1) {\n";
    main_ss << "        nes_run_frame(ctx);\n";
    main_ss << "        if (!nes_platform_poll_events(ctx)) break;\n";
    main_ss << "        if (ctx->frame_done) {\n";
    main_ss << "            const uint32_t* fb = nes_get_framebuffer(ctx);\n";
    main_ss << "            if (fb) nes_platform_render_frame(fb);\n";
    main_ss << "            nes_reset_frame(ctx);\n";
    main_ss << "            ctx->stopped = 0;\n";
    main_ss << "            nes_platform_vsync();\n";
    main_ss << "        }\n";
    main_ss << "    }\n";
    main_ss << "    nes_platform_shutdown();\n";
    main_ss << "#else\n";
    main_ss << "    // No SDL2 - just run for testing\n";
    main_ss << "    " << options.output_prefix << "_run(ctx);\n";
    main_ss << "    printf(\"Recompiled code executed successfully!\\n\");\n";
    main_ss << "    printf(\"Registers: A=%02X X=%02X Y=%02X\\n\", ctx->a, ctx->x, ctx->y);\n";
    main_ss << "#endif\n";
    main_ss << "\n";
    main_ss << "    nes_context_destroy(ctx);\n";
    main_ss << "    return 0;\n";
    main_ss << "}\n";
    output.main_content = main_ss.str();
    output.main_file = options.output_prefix + "_main.c";
    
    // Generate CMakeLists.txt
    std::ostringstream cmake_ss;
    cmake_ss << "cmake_minimum_required(VERSION 3.16)\n";
    cmake_ss << "project(" << options.output_prefix << " C CXX)\n\n";
    cmake_ss << "# Set C standard\n";
    cmake_ss << "set(CMAKE_C_STANDARD 11)\n";
    cmake_ss << "set(CMAKE_C_STANDARD_REQUIRED ON)\n\n";
    cmake_ss << "# Aggressive optimization flags\n";
    cmake_ss << "if(NOT CMAKE_BUILD_TYPE)\n";
    cmake_ss << "    set(CMAKE_BUILD_TYPE Release)\n";
    cmake_ss << "endif()\n";
    cmake_ss << "if(CMAKE_C_COMPILER_ID MATCHES \"GNU|Clang\")\n";
    cmake_ss << "    add_compile_options(-O3)\n";
    cmake_ss << "endif()\n\n";
    // Calculate relative path to runtime
    namespace fs = std::filesystem;
    fs::path out_path(options.output_dir);
    std::string runtime_path;
    
    // Count depth to generate correct number of ../
    int depth = 0;
    for (const auto& p : out_path) {
        if (p == ".") continue;
        depth++;
    }
    // Ensure at least one level up
    if (depth == 0) depth = 1;

    std::stringstream rt_ss;
    for(int i=0; i<depth; i++) rt_ss << "../";
    rt_ss << "runtime";
    runtime_path = rt_ss.str();

    cmake_ss << "# Runtime library path (relative to this output directory)\n";
    cmake_ss << "set(NESRT_DIR \"${CMAKE_CURRENT_SOURCE_DIR}/" << runtime_path << "\")\n\n";
    cmake_ss << "# Find SDL2\n";
    cmake_ss << "find_package(SDL2 REQUIRED)\n\n";
    cmake_ss << "# Create runtime library with PPU and platform support\n";
    cmake_ss << "add_library(nesrt STATIC\n";
    cmake_ss << "    ${NESRT_DIR}/src/nesrt.c\n";
    cmake_ss << "    ${NESRT_DIR}/src/ppu.c\n";
    cmake_ss << "    ${NESRT_DIR}/src/audio.c\n";
    cmake_ss << "    ${NESRT_DIR}/src/audio_stats.c\n";
    cmake_ss << "    ${NESRT_DIR}/src/interpreter.c\n";
    cmake_ss << "    ${NESRT_DIR}/src/mapper.c\n";
    cmake_ss << "    ${NESRT_DIR}/src/nesrt_trace.c\n";
    cmake_ss << "    ${NESRT_DIR}/src/platform_sdl.cpp\n";
    cmake_ss << ")\n\n";

    cmake_ss << "# ImGui sources\n";
    cmake_ss << "target_sources(nesrt PRIVATE\n";
    cmake_ss << "    ${NESRT_DIR}/third_party/imgui/imgui.cpp\n";
    cmake_ss << "    ${NESRT_DIR}/third_party/imgui/imgui_draw.cpp\n";
    cmake_ss << "    ${NESRT_DIR}/third_party/imgui/imgui_tables.cpp\n";
    cmake_ss << "    ${NESRT_DIR}/third_party/imgui/imgui_widgets.cpp\n";
    cmake_ss << "    ${NESRT_DIR}/third_party/imgui/imgui_demo.cpp\n";
    cmake_ss << "    ${NESRT_DIR}/third_party/imgui/backends/imgui_impl_sdl2.cpp\n";
    cmake_ss << "    ${NESRT_DIR}/third_party/imgui/backends/imgui_impl_sdlrenderer2.cpp\n";
    cmake_ss << ")\n";

    cmake_ss << "target_include_directories(nesrt PUBLIC \n";
    cmake_ss << "    ${NESRT_DIR}/include\n";
    cmake_ss << "    ${NESRT_DIR}/third_party/imgui\n";
    cmake_ss << ")\n";
    cmake_ss << "target_link_libraries(nesrt PUBLIC SDL2::SDL2)\n";
    cmake_ss << "target_compile_definitions(nesrt PUBLIC NES_HAS_SDL2)\n";
    cmake_ss << "target_compile_definitions(nesrt PUBLIC NESRT_TRACE_ENABLED)\n\n";
    cmake_ss << "# Main executable\n";
    cmake_ss << "add_executable(" << options.output_prefix << "\n";
    cmake_ss << "    " << options.output_prefix << "_main.c\n";
    cmake_ss << "    " << options.output_prefix << ".c\n";
    cmake_ss << "    " << options.output_prefix << "_rom.c\n";
    cmake_ss << ")\n\n";
    cmake_ss << "target_link_libraries(" << options.output_prefix << " nesrt)\n";
    output.cmake_content = cmake_ss.str();
    output.cmake_file = "CMakeLists.txt";
    
    return output;
}

bool write_output(const GeneratedOutput& output, const std::string& output_dir) {
    namespace fs = std::filesystem;
    
    try {
        // Create output directory if it doesn't exist
        fs::path out_path(output_dir);
        if (!fs::exists(out_path)) {
            fs::create_directories(out_path);
        }
        
        // Write header file
        std::ofstream header_file(out_path / output.header_file);
        if (!header_file) return false;
        header_file << output.header_content;
        header_file.close();
        
        // Write source file
        std::ofstream source_file(out_path / output.source_file);
        if (!source_file) return false;
        source_file << output.source_content;
        source_file.close();
        
        // Write ROM data file
        std::ofstream rom_file(out_path / output.rom_data_file);
        if (!rom_file) return false;
        rom_file << output.rom_data_content;
        rom_file.close();
        
        // Write main file
        std::ofstream main_file(out_path / output.main_file);
        if (!main_file) return false;
        main_file << output.main_content;
        main_file.close();
        
        // Write CMakeLists.txt
        std::ofstream cmake_file(out_path / output.cmake_file);
        if (!cmake_file) return false;
        cmake_file << output.cmake_content;
        cmake_file.close();
        
        return true;
    } catch (...) {
        return false;
    }
}

} // namespace codegen
} // namespace nesrecomp
